import turtle
Rafael = turtle.Turtle()
Rafael.color("red")
Rafael.forward(60)
Rafael.left(90)
Rafael.forward(50)
Rafael.left(90)
Rafael.forward(15)
Rafael.right(135)
Rafael.forward(70)
Rafael.right(90)
Rafael.forward(70)
Rafael.right(135)
Rafael.forward(15)
Rafael.left(90)
Rafael.forward(50)
Rafael.left(90)
Rafael.forward(60)
Rafael.right(180)
Rafael.forward(88)
Rafael.right(90)
Rafael.forward(25)
Rafael.left(90)
Rafael.forward(10)
Rafael.left(90)
Rafael.forward(25)
Rafael.right(90)
Rafael.forward(90)

Rafael = turtle.Turtle()
Rafael.color("red")
Rafael.right(360)
Rafael.forward(78)
Rafael.color("white")
Rafael.left(90)
Rafael.forward(35)

Rafael.color("red")
Rafael.left(90)
Rafael.forward(10)
Rafael.right(90)
Rafael.forward(10)
Rafael.right(90)
Rafael.forward(20)
Rafael.right(90)
Rafael.forward(10)
Rafael.right(90)
Rafael.forward(10)

Rafael.color("red")
Rafael.right(180)
Rafael.forward(11)

Rafael.color("white")
Rafael.forward(10)

Rafael.color("red")
Rafael.left(90)
Rafael.forward(10)
Rafael.right(90)
Rafael.forward(20)
Rafael.right(90)
Rafael.forward(10)
Rafael.right(90)
Rafael.forward(20)
Rafael.right(90)
Rafael.forward(14)

Rafael.color("white")
Rafael.forward(2)

Rafael.color("red")
Rafael.right(90)
Rafael.forward(40)
Rafael.right(180)
Rafael.forward(80)